### ISSUE TITLE
How can I run this?

### ISSUE THREAD

**Issue by Norbajusz** [KarboniteKream/JC2MapViewer#7]
I'm not very versed in coding, but I don't see any executables among the files to run this. Please help. From what I've seen when searching, there should be a 'bin' folder where the .exe is located, but it's missing.

**Comment by KarboniteKream** [comment]
You can find the ZIP file [here](https://github.com/KarboniteKream/JC2MapViewer/releases/tag/0.3.5), which contains the executable.
